spring:

  application:
    name: vibify

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: 8080

r2:
  endpoint: ${R2_ENDPOINT}
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}
  bucket: ${R2_BUCKET}
  publicUrl: ${R2_PUBLIC_URL}