package com.vibify.websocket.event;

public enum RoomEventType {

    PLAYBACK_SONG_STARTED,
    PLAYBACK_PLAYLIST_STARTED,
    PLAYBACK_PAUSED,
    PLAYBACK_RESUMED,
    PLAYBACK_SEEKED,
    PLAYBACK_SKIPPED,
    PLAYBACK_STOPPED,

    QUEUE_ITEM_ADDED,
    QUEUE_ITEM_REMOVED,
    QUEUE_ITEM_REORDERED,
    QUEUE_CLEARED,
    QUEUE_REPLACED,

    ROOM_STATE_SYNC,

    PLAYBACK_STATE_SYNC,

    ROOM_MEMBER_JOINED,
    ROOM_MEMBER_LEFT,

    ROOM_ENDED,

    ///CHAT EVENTS
    CHAT_MESSAGE_SENT,
    CHAT_MESSAGE_SEEN,
    CHAT_MESSAGE_DELETED,
    TYPING_STARTED,
    TYPING_STOPPED,
    CHAT_MESSAGES_SYNC,

    VOICE_START,
    VOICE_STOP
}